Repository CA-G12/words, pull requests merged in 2022-09, with the labels that each got.

#2 file structure
  words-app/.gitignore
  words-app/README.md
  words-app/package-lock.json
  words-app/package.json
  words-app/public/favicon.ico
  words-app/public/index.html
  words-app/public/logo192.png
  words-app/public/logo512.png
  words-app/public/manifest.json
  words-app/public/robots.txt
  words-app/src/App.css
  words-app/src/App.js
  words-app/src/App.test.js
  words-app/src/components/Card.js
  words-app/src/components/Header.js
  words-app/src/index.css
  words-app/src/index.js
  words-app/src/reportWebVitals.js
  words-app/src/setupTests.js
  words-app/src/utils/getWordData.js
Labels: approved

#4 fetch data
  words-app/src/App.js
  words-app/src/utils/getWordData.js
Labels: merged

#6 get input data
  words-app/src/App.js
  words-app/src/components/Bookmark.js
  words-app/src/components/Card.js
  words-app/src/components/Header.js
  words-app/src/utils/getWordData.js
Labels: awating-review

#9 refactor header into classes component
  words-app/src/components/Card.js
  words-app/src/components/Header.js
Labels: merged
